#!/usr/bin/env python3
"""
Shared guard logic to keep explicit AI usage indicators out of commits.

This script supports two entry points:
  * pre-commit  - scan staged diffs for blocked phrases
  * commit-msg  - reject commit messages that reference AI tooling
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

PATTERN_STRINGS: Sequence[str] = (
    r"generated by cursor",
    r"cursor ai",
    r"cursor wrote this",
    r"cursor suggestion",
    r"generated by claude",
    r"claude wrote this",
    r"claude ai",
    r"claude opus",
    r"claude sonnet",
    r"claude haiku",
    r"claude code",
    r"generated with claude code",
    r"generated with \[claude code\]",
    r"co-authored-by: claude",
    r"noreply@anthropic\.com",
    r"generated by gemini",
    r"gemini wrote this",
    r"google gemini",
    r"gemini ultra",
    r"gemini pro",
    r"gemini nano",
    r"generated by bard",
    r"bard wrote this",
    r"google bard",
    r"as an ai assistant",
    r"as an ai",
    r"ai assistant",
    r"ai suggestion",
    r"ai suggestions",
    r"ai-generated",
    r"ai generated",
    r"ai-assisted",
    r"ai assisted",
    r"ai-powered",
    r"ai powered",
    r"powered by ai",
    r"with ai assistance",
    r"with the help of ai",
    r"assisted by ai",
    r"written with ai",
    r"written by ai",
    r"generated with ai",
    r"generated via ai",
    r"created with ai",
    r"created by ai",
    r"authored by ai",
    r"co-authored by ai",
    r"ai help",
    r"ai helped",
    r"ai copilot",
    r"ai co-pilot",
    r"chatgpt",
    r"gpt-4",
    r"gpt4",
    r"gpt-3",
    r"gpt3",
    r"openai",
    r"anthropic",
    r"google ai",
    r"google deepmind",
    r"deepmind",
    r"perplexity",
    r"perplexity ai",
    r"tabnine",
    r"tabnine ai",
    r"replit ghostwriter",
    r"ghostwriter ai",
    r"aws codewhisperer",
    r"amazon codewhisperer",
    r"code whisperer",
    r"codewhisperer",
    r"github copilot",
    r"copilot",
    r"amazon q",
    r"amazon q developer",
    r"meta ai",
    r"deepseek",
    r"phind",
    r"blackbox ai",
    r"magic ai",
    r"ai model",
    r"llm",
    r"large language model",
    r"language model",
    r"\[ai\]",
    r"\[ai-generated\]",
    r"\[cursor\]",
    r"\[claude\]",
    r"\[gemini\]",
    r"\[copilot\]",
    r"\[chatgpt\]",
    r"\[llm\]",
)

PATTERN_REGEXES: Sequence[Tuple[str, re.Pattern[str]]] = tuple(
    (pattern, re.compile(pattern, re.IGNORECASE))
    for pattern in PATTERN_STRINGS
)

BLOCK_PREFIX = "✖"


def detect_pattern(text: str) -> Optional[str]:
    """Return the raw pattern that matches ``text`` (case-insensitive)."""
    for raw, regex in PATTERN_REGEXES:
        if regex.search(text):
            return raw
    return None


def gather_binary_paths(diff_filter: Sequence[str]) -> set[str]:
    """
    Return the paths Git reports as binary for the given diff filter.

    This mirrors the logic used by `git diff --numstat` where additions or
    deletions are reported as "-" for binary files.
    """
    filter_arg = "".join(diff_filter)
    cmd = ["git", "diff", "--cached", "--numstat", f"--diff-filter={filter_arg}"]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    binary_paths: set[str] = set()
    for line in proc.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        added, deleted, path = parts
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        if added == "-" or deleted == "-":
            binary_paths.add(path)
    return binary_paths


def run_pre_commit(diff_filter: Sequence[str]) -> int:
    """Scan staged additions for blocked patterns."""
    filter_arg = "".join(diff_filter)
    binary_paths = gather_binary_paths(diff_filter)
    cmd = [
        "git",
        "diff",
        "--cached",
        f"--diff-filter={filter_arg}",
        "--unified=0",
        "--no-color",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    report: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
    current_file: Optional[str] = None

    for line in proc.stdout.splitlines():
        if line.startswith("diff --git "):
            current_file = None
            continue
        if line.startswith("+++ "):
            current_file = _normalise_diff_path(line[4:])
            continue
        if line.startswith("Binary files "):
            current_file = None
            continue
        if not line.startswith("+") or line.startswith("+++ "):
            continue
        if not current_file:
            continue
        if current_file in binary_paths:
            continue
        content = line[1:]
        if not content:
            continue
        pattern = detect_pattern(content)
        if pattern:
            report[current_file].append((line, pattern))

    if report:
        lines = [
            f"{BLOCK_PREFIX} Commit blocked: staged changes contain AI usage indicators in the current diff.",
            "Please remove or rephrase the highlighted additions before committing:",
        ]
        for path, entries in report.items():
            lines.append(f"• {path}")
            for addition, _pattern in entries:
                lines.append(f"  {addition}")
        sys.stderr.write("\n".join(lines) + "\n")
        return 1
    return 0


def run_commit_msg(message_path: Path) -> int:
    """Reject commit messages referencing AI tooling."""
    try:
        content = message_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        sys.stderr.write(f"{BLOCK_PREFIX} Commit message blocked: file not found: {message_path}\n")
        return 1

    pattern = detect_pattern(content)
    if pattern:
        lines = [
            f"{BLOCK_PREFIX} Commit message blocked: found AI indicator matching `{pattern}`.",
            "",
            "Please rewrite the message without explicitly referencing AI tools or prompts.",
        ]
        sys.stderr.write("\n".join(lines) + "\n")
        return 1
    return 0


def _normalise_diff_path(path_fragment: str) -> Optional[str]:
    """Strip diff prefixes to obtain a repository-relative path."""
    path_fragment = path_fragment.strip()
    if path_fragment.startswith("b/"):
        return path_fragment[2:]
    if path_fragment.startswith("a/"):
        return path_fragment[2:]
    if path_fragment == "/dev/null":
        return None
    return path_fragment or None


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Block AI usage indicators during git workflows.",
    )
    parser.add_argument(
        "stage",
        choices=("pre-commit", "commit-msg"),
        help="Hook stage that invoked the guard.",
    )
    parser.add_argument(
        "extra",
        nargs="*",
        help="Additional arguments supplied by git (e.g. commit message path).",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if args.stage == "pre-commit":
        return run_pre_commit(diff_filter=("A", "C", "M", "R", "T"))
    if args.stage == "commit-msg":
        if not args.extra:
            sys.stderr.write(f"{BLOCK_PREFIX} Commit message blocked: missing message path argument.\n")
            return 1
        return run_commit_msg(Path(args.extra[0]))
    sys.stderr.write(f"{BLOCK_PREFIX} Unknown stage: {args.stage}\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
